#!/usr/bin/env node
/**
 * Stop hook (strict): runs the project's configured verification commands on
 * stop (lint, types). On a real failure it blocks so Claude fixes it before
 * finishing. Generated by aia-harness — fail-open on infra: a missing runtime
 * or command never blocks. Re-run /aia-harness:doctor to audit.
 */
import fs from "node:fs";
import path from "node:path";
import { execSync, execFileSync } from "node:child_process";
import { sessionScratchDir } from "./session-scratch.mjs";

// `scoped: true` appends this session's changed files to the command, so a
// project with pre-existing lint debt only gates on what this session touched.
// `exts` is what the tool can actually parse — both of these are Python-only, so
// handing them the .mjs hooks in this very directory makes them report the
// JavaScript as broken Python.
const PY = /\.(py|pyi)$/;
const COMMANDS = [
  {"label":"lint","cmd":"ruff check","scoped":true,"exts":PY},
  {"label":"typecheck","cmd":"pyright","scoped":true,"exts":PY},
];
const projectDir = process.env.CLAUDE_PROJECT_DIR || process.cwd();

/**
 * Prefer the project venv's binary over a bare name. Hooks inherit Claude Code's
 * env, which usually has no activated venv — a bare `ruff` then throws ENOENT and
 * the strict gate silently never runs. Same probe format-on-edit.mjs uses.
 * @param {string} name
 * @returns {string}
 */
function resolveBin(name) {
  const venvDir = process.platform === "win32" ? "Scripts" : "bin";
  const exe = process.platform === "win32" ? name + ".exe" : name;
  const local = path.join(projectDir, ".venv", venvDir, exe);
  return fs.existsSync(local) ? local : name;
}
/** A changed file is relevant only if some configured command can read it. */
function isLintable(p) {
  return COMMANDS.some((c) => c.exts.test(p));
}

let event = {};
try { event = JSON.parse(fs.readFileSync(0, "utf8") || "{}"); } catch (e) { process.exit(0); }
const sessionId = typeof event?.session_id === "string" ? event.session_id : "nosession";

function flagFile() {
  return path.join(sessionScratchDir(sessionId), "files-changed");
}
function clearFlag() {
  try { fs.rmSync(flagFile(), { force: true }); } catch (e) { /* ignore */ }
}
function approve() {
  process.stdout.write(JSON.stringify({ decision: "approve" }));
  process.exit(0);
}

// Anti-loop: a stop already triggered by a previous block must be allowed.
if (event && event.stop_hook_active) { clearFlag(); approve(); }

const flag = flagFile();
if (!fs.existsSync(flag)) approve(); // session changed nothing

// event.cwd tracks EnterWorktree, so this is the checkout actually being edited.
const execDir = (event && typeof event.cwd === "string" && event.cwd) || projectDir;

/**
 * Gate only on files inside the project. A session routinely writes .py scratch
 * files under the temp dir (test fixtures, throwaway scripts); those are not the
 * project's code and must not block the stop — nor be fed to a linter configured
 * for this repo.
 * @param {string} p
 */
function insideProject(p) {
  const rel = path.relative(execDir, path.resolve(p));
  return rel !== "" && !rel.startsWith("..") && !path.isAbsolute(rel);
}

let changed = "";
try { changed = fs.readFileSync(flag, "utf8"); } catch (e) { approve(); }
const lintable = Array.from(new Set(changed.split("\n").map(function (p) { return p.trim(); })))
  .filter(function (p) { return p && isLintable(p) && insideProject(p) && fs.existsSync(p); });
if (lintable.length === 0) { clearFlag(); approve(); }

// Ensure the active node's dir (nvm/fnm/system node) is on PATH for the run.
// process.execPath is always the actual running binary — works with any node manager.
const binDir = path.dirname(process.execPath);
const env = Object.assign({}, process.env, { PATH: binDir + path.delimiter + (process.env.PATH || "") });
const failures = [];
for (const entry of COMMANDS) {
  try {
    if (entry.scoped) {
      const targets = lintable.filter(function (p) { return entry.exts.test(p); });
      if (targets.length === 0) continue; // nothing this tool can read
      // No shell: file paths go through as argv, so they can never be interpreted.
      const parts = entry.cmd.split(/\s+/);
      execFileSync(resolveBin(parts[0]), parts.slice(1).concat(targets), { cwd: execDir, env: env, timeout: 120000, stdio: ["ignore", "pipe", "pipe"] });
    } else {
      execSync(entry.cmd, { cwd: execDir, env: env, timeout: 120000, stdio: ["ignore", "pipe", "pipe"] });
    }
  } catch (err) {
    // ENOENT / exit 127 = command or runtime missing -> infra, fail open.
    if (err.code === "ENOENT" || err.status === 127) continue;
    const out = ((err.stdout ? err.stdout.toString() : "") + (err.stderr ? err.stderr.toString() : "")).trim();
    failures.push({ label: entry.label, cmd: entry.cmd, out: out || err.message || (entry.label + " failed") });
  }
}

if (failures.length === 0) { clearFlag(); approve(); }

let lines = [];
for (const f of failures) {
  lines.push("=== " + f.label + " (" + f.cmd + ") failed ===");
  lines = lines.concat(f.out.split("\n"));
  lines.push("");
}
const excerpt = lines.slice(0, 80).join("\n");
const truncated = lines.length > 80 ? "\n...(" + (lines.length - 80) + " more lines)" : "";

// Stop schema: top-level decision + reason only (no hookSpecificOutput channel).
process.stdout.write(JSON.stringify({
  decision: "block",
  reason: "Fix all lint/type errors below before finishing.\n\n" + excerpt + truncated
}));
process.exit(0);
